In [3]:
from xlseries import XlSeries
from xlseries.utils.path_finders import get_orig_cases_path, get_param_cases_path

In [4]:
series = XlSeries(get_orig_cases_path(1))
dfs = series.get_data_frames(get_param_cases_path(1))

In [6]:
dfs[0][1]

            IPC-CqP  Var. Anual
1993-01   48.456885         NaN
1993-02   48.810834         NaN
1993-03   49.177819         NaN
1993-04   49.691889         NaN
1993-05   50.331205         NaN
1993-06   50.693241         NaN
1993-07   50.856318         NaN
1993-08   50.864473         NaN
1993-09   51.283639         NaN
1993-10   51.573538         NaN
1993-11   51.603020         NaN
1993-12   51.596247         NaN
1994-01   51.648201         NaN
1994-02   51.646377         NaN
1994-03   51.718368         NaN
1994-04   51.844260         NaN
1994-05   52.023953         NaN
1994-06   52.225279         NaN
1994-07   52.707442         NaN
1994-08   52.816187         NaN
1994-09   53.177668         NaN
1994-10   53.348073         NaN
1994-11   53.468687         NaN
1994-12   53.584964         NaN
1995-01   54.252619         NaN
1995-02   54.251135         NaN
1995-03   54.007392         NaN
1995-04   54.254386         NaN
1995-05   54.265791         NaN
1995-06   54.154034         NaN
...             ...         ...
2011-10  273.656194    0.245580
2011-11  277.730271    0.239428
2011-12  282.952493    0.242041
2012-01  286.945900    0.234839
2012-02  292.103099    0.239792
2012-03  297.927227    0.238038
2012-04  304.926716    0.240220
2012-05  310.068516    0.236638
2012-06  315.049053    0.233858
2012-07  321.752025    0.234281
2012-08  328.412102    0.237076
2012-09  334.006553    0.233541
2012-10  339.092535    0.239119
2012-11  345.608751    0.244404
2012-12  351.866109    0.243552
2013-01  358.256322    0.248515
2013-02  364.029165    0.246235
2013-03  369.703958    0.240920
2013-04  375.799277    0.232425
2013-05  381.878851    0.231595
2013-06  389.087144    0.235005
2013-07  398.719694    0.239214
2013-08  406.749239    0.238533
2013-09  414.060546    0.239678
2013-10  425.587402    0.255077
2013-11  437.313582    0.265343
2013-12  448.588774    0.274885
2014-01  469.161388    0.309569
2014-02  491.818800    0.351042
2014-03  508.186408    0.374577

[255 rows x 2 columns]